#include <QtCore/qglobal.h>
#include "vh_logging.h"
#include "vfqml_export.h"


Q_DECLARE_LOGGING_CATEGORY(VEIN_API_QML)
Q_DECLARE_LOGGING_CATEGORY(VEIN_API_QML_VERBOSE)
Q_DECLARE_LOGGING_CATEGORY(VEIN_API_QML_INTROSPECTION)
