#ifndef QMLVEINENTITY_GLOBAL_H
#define QMLVEINENTITY_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(VEIN_API_QML)
Q_DECLARE_LOGGING_CATEGORY(VEIN_API_QML_VERBOSE)
Q_DECLARE_LOGGING_CATEGORY(VEIN_API_QML_INTROSPECTION)

#if defined(QMLVEINENTITY_LIBRARY)
#  define QMLVEINENTITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMLVEINENTITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMLVEINENTITY_GLOBAL_H
